const users = [
  {
    id: 1,
    first_name: "Cammie",
    last_name: "Sherwood",
    email: "csherwood0@pbs.org",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Willey",
    last_name: "Woffinden",
    email: "wwoffinden1@addtoany.com",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Lynnell",
    last_name: "Lace",
    email: "llace2@blogger.com",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Rosie",
    last_name: "Dukes",
    email: "rdukes3@home.pl",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Kerrill",
    last_name: "Anneslie",
    email: "kanneslie4@archive.org",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Arnie",
    last_name: "Penritt",
    email: "apenritt5@tinypic.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Charmian",
    last_name: "Hugonneau",
    email: "chugonneau6@disqus.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Luella",
    last_name: "Gillaspy",
    email: "lgillaspy7@techcrunch.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Tedda",
    last_name: "Bristow",
    email: "tbristow8@vinaora.com",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Krystalle",
    last_name: "Radleigh",
    email: "kradleigh9@sakura.ne.jp",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Jory",
    last_name: "Brandel",
    email: "jbrandela@ted.com",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Ezequiel",
    last_name: "Ponte",
    email: "eponteb@unicef.org",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Devland",
    last_name: "McCambrois",
    email: "dmccambroisc@examiner.com",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Essy",
    last_name: "Cuddihy",
    email: "ecuddihyd@tripadvisor.com",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Neille",
    last_name: "Navarro",
    email: "nnavarroe@ebay.com",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Emmaline",
    last_name: "Kolis",
    email: "ekolisf@woothemes.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Trever",
    last_name: "Madre",
    email: "tmadreg@canalblog.com",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Jordana",
    last_name: "Bailles",
    email: "jbaillesh@cbslocal.com",
    gender: "Non-binary",
  },
  {
    id: 19,
    first_name: "Kara",
    last_name: "Yesinin",
    email: "kyesinini@oakley.com",
    gender: "Female",
  },
  {
    id: 20,
    first_name: "Van",
    last_name: "Hanes",
    email: "vhanesj@miibeian.gov.cn",
    gender: "Male",
  },
  {
    id: 21,
    first_name: "Kaspar",
    last_name: "Altham",
    email: "kalthamk@tmall.com",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Hugo",
    last_name: "Kynder",
    email: "hkynderl@e-recht24.de",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Jeane",
    last_name: "Kenafaque",
    email: "jkenafaquem@aol.com",
    gender: "Female",
  },
  {
    id: 24,
    first_name: "Pieter",
    last_name: "Kemmons",
    email: "pkemmonsn@umich.edu",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Griswold",
    last_name: "Cubitt",
    email: "gcubitto@dion.ne.jp",
    gender: "Male",
  },
  {
    id: 26,
    first_name: "Orlan",
    last_name: "Fearnyhough",
    email: "ofearnyhoughp@go.com",
    gender: "Male",
  },
  {
    id: 27,
    first_name: "Morey",
    last_name: "Curmi",
    email: "mcurmiq@cornell.edu",
    gender: "Male",
  },
  {
    id: 28,
    first_name: "Timothy",
    last_name: "Kezor",
    email: "tkezorr@marriott.com",
    gender: "Male",
  },
  {
    id: 29,
    first_name: "Freddie",
    last_name: "Willstrop",
    email: "fwillstrops@paypal.com",
    gender: "Female",
  },
  {
    id: 30,
    first_name: "Keith",
    last_name: "Gozzett",
    email: "kgozzettt@slideshare.net",
    gender: "Male",
  },
  {
    id: 31,
    first_name: "Clair",
    last_name: "Harsum",
    email: "charsumu@arizona.edu",
    gender: "Male",
  },
  {
    id: 32,
    first_name: "Felice",
    last_name: "Kennaird",
    email: "fkennairdv@stumbleupon.com",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Barret",
    last_name: "Husher",
    email: "bhusherw@unc.edu",
    gender: "Male",
  },
  {
    id: 34,
    first_name: "Ninnetta",
    last_name: "Marfell",
    email: "nmarfellx@ask.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Humberto",
    last_name: "Fansy",
    email: "hfansyy@reuters.com",
    gender: "Non-binary",
  },
  {
    id: 36,
    first_name: "Ewan",
    last_name: "Tideswell",
    email: "etideswellz@gmpg.org",
    gender: "Male",
  },
  {
    id: 37,
    first_name: "Guenna",
    last_name: "Leith-Harvey",
    email: "gleithharvey10@tinypic.com",
    gender: "Female",
  },
  {
    id: 38,
    first_name: "Nanni",
    last_name: "Halfhide",
    email: "nhalfhide11@soup.io",
    gender: "Female",
  },
  {
    id: 39,
    first_name: "Lexy",
    last_name: "Billo",
    email: "lbillo12@blogtalkradio.com",
    gender: "Female",
  },
  {
    id: 40,
    first_name: "Jamesy",
    last_name: "Greves",
    email: "jgreves13@instagram.com",
    gender: "Male",
  },
  {
    id: 41,
    first_name: "Marco",
    last_name: "Turpin",
    email: "mturpin14@imageshack.us",
    gender: "Male",
  },
  {
    id: 42,
    first_name: "Timi",
    last_name: "Dixon",
    email: "tdixon15@godaddy.com",
    gender: "Female",
  },
  {
    id: 43,
    first_name: "Karlotte",
    last_name: "Kuschek",
    email: "kkuschek16@google.ca",
    gender: "Female",
  },
  {
    id: 44,
    first_name: "Sydelle",
    last_name: "Tolan",
    email: "stolan17@list-manage.com",
    gender: "Female",
  },
  {
    id: 45,
    first_name: "Corrine",
    last_name: "Claworth",
    email: "cclaworth18@tamu.edu",
    gender: "Female",
  },
  {
    id: 46,
    first_name: "Janella",
    last_name: "Flamank",
    email: "jflamank19@redcross.org",
    gender: "Female",
  },
  {
    id: 47,
    first_name: "Simone",
    last_name: "Karel",
    email: "skarel1a@ucoz.com",
    gender: "Male",
  },
  {
    id: 48,
    first_name: "Lauri",
    last_name: "Domleo",
    email: "ldomleo1b@nifty.com",
    gender: "Female",
  },
  {
    id: 49,
    first_name: "Travis",
    last_name: "Poate",
    email: "tpoate1c@google.cn",
    gender: "Genderqueer",
  },
  {
    id: 50,
    first_name: "Lurleen",
    last_name: "Cowthard",
    email: "lcowthard1d@sogou.com",
    gender: "Female",
  },
];

export const getUsers = (page, limit) => {
  let array = [];
  for (let i = (page - 1) * limit; i < page * limit && users[i]; i++) {
    array.push(users[i]);
  }
  return array;
};

export const getLength = () => {
  return users?.length;
};
